name: Deploy to AWS EC2

on:
  push:
    paths:
      - 'Assignment_3/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@44.202.92.141 << 'EOF'
            # Navigate to the project directory
            cd /home/ubuntu/Dicecamp-12/Assignment_3

            # Pull the latest changes from the repository
            git pull origin main

            # Stop existing containers
            docker-compose down

            # Build and start containers
            docker-compose up -d --build
          EOF

