name: Deploy to AWS EC2

on:
  push:
    paths:
      - 'Assignment 3/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r Assignment\ 3/* ec2-user@<your-ec2-ip>:/var/www/html/

      - name: Build and run Docker container
        run: |
          ssh ec2-user@<your-ec2-ip> 'cd /var/www/html && docker build -t my-php-app . && docker run -d -p 80:80 my-php-app'
