name: Deploy on EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

#      - name: Set up SSH
#        run: |
#          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
#          chmod 600 key.pem


      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          
      - name: Adding EC2 to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: List files in the repository
        run: ls -R

      - name: Copy files to the EC2 Instance
        run: |
          # Print the current directory to debug path issues
          pwd
          whoami
          # Print the directory contents to confirm the file structure
          ls -la
          # Copy files to EC2 instance
          scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no -r /home/runner/work/Dicecamp-12/Dicecamp-12/Assignment_3/ ubuntu@${{ secrets.HOST_DNS }}:/home/ubuntu/

#         scp -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no -r ./Assignment_3/ ubuntu@${{ secrets.HOST_DNS }}:/home/ubuntu/
#         scp -i key.pem -o StrictHostKeyChecking=no  -r ./Dicecamp-12/Assignment_3/ ubuntu@${{ secrets.HOST_DNS }}:/home/ubuntu/


#      - name: Deploy Docker Container on EC2 instances
#        run: |
#          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
#            cd /home/ubuntu/Assignment_3/
#            docker-compose down || true
#            docker-compose build
#            docker-compose up -d
#          EOF

#      - name: Verification
#        run: |
#          curl http://${{ secrets.HOST_DNS }}/index.html

#      - name: Set up SSH
#        run: |
#          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
#          chmod 600 key.pem

      

 #     - name: Prepare deployment script
 #       run: |
 #         echo "#!/bin/bash" > deploy.sh
 #         echo "sudo apt update && sudo apt upgrade -y" >> deploy.sh
 #         echo "docker stop php-ec2-git || true" >> deploy.sh
 #         echo "docker rm php-ec2-git || true" >> deploy.sh
 #         echo "docker rmi assignment3-php-image || true" >> deploy.sh
 #         echo "docker-compose up -d --build" >> deploy.sh
 #         chmod +x deploy.sh

#      - name: SCP Files to Deploy Application
#        run: |
#          scp -i key.pem -o StrictHostKeyChecking=no deploy.sh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu
#          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} 'sudo bash /home/ubuntu/deploy.sh'
      
#      - name: Clean Up
#        run: |
#          rm -f key.pem
