name: Deploy on EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Prepare deployment script
        run: |
          echo "#!/bin/bash" > deploy.sh
          echo "sudo apt update && sudo apt upgrade -y" >> deploy.sh
          echo "docker stop php-ec2-git || true" >> deploy.sh
          echo "docker rm php-ec2-git || true" >> deploy.sh
          echo "docker rmi assignment3-php-image || true" >> deploy.sh
          echo "docker-compose up -d --build" >> deploy.sh
          chmod +x deploy.sh

      - name: Dploy Application
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no deploy.sh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} 'sudo bash /home/ubuntu/deploy.sh'
      
      - name: Clean Up
        run: |
          rm -f key.pem
