name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Update and upgrade packages
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          sudo apt-get update
          sudo apt-get upgrade -y
        EOF

    - name: Install or update Docker
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          sudo apt-get install -y docker.io
        EOF

    - name: Stop and remove existing Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          docker stop php-ec2-git || true
          docker rm php-ec2-git || true
        EOF

    - name: Build Docker image
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          docker build -t assignment3-php-image:latest .
        EOF

    - name: Run Docker container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          docker run -d --name php-ec2-git -p 80:80 assignment3-php-image:latest
        EOF
